### ISSUE TITLE
Does this code requires the device on Wifi?

### ISSUE THREAD

**Issue by deeeprun** [rpng/reach_ros_node#5]
Does the code support Emlid Reach M+ and requires the device on Wifi?

**Comment by goldbattle** [comment]
I don't have a Reach M+ to test with as we use the original Reach devices, but I don't see a reason for it not working since they all use the same [ReachView backend](https://docs.emlid.com/reachm-plus/common/reachview/position-output/#tcp). You need to connect to the device somehow, either through usb which opens an ethernet connection to the device last time I checked. Normally I tether everything to a phone and go through that when I use it. Hope this helps.

**Comment by ArtlyStyles** [comment]
How do you connect Reach M+ with Reach RS+. Actually, I am not sure what is the difference between the two

**Comment by goldbattle** [comment]
I would recommend asking for the forums as compared to here. This is software for getting the corrected output once you have already connected the two, or just for a single Reach M+ if you only have that. I would recommend looking at the documentation:
https://docs.emlid.com/reachrs/common/quickstart/base-rover-setup/
